collections:
  diary:
    output: true
    permalink: /blog/diary/data/:name/
markdown_ext: "md"
future: true
defaults:
    - scope:
      path: "_diary"
      type: "diary"
    values:
      layout: "diary"
